<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DecryptPassword">
      <HintPath>..\..\DecryptPassword\DecryptPassword\bin\Debug\DecryptPassword.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
